// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestProject1
{
    using System;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Windows.Input;
    using System.CodeDom.Compiler;
    using System.Text.RegularExpressions;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCodeAttribute("Coded UITest Builder", "10.0.20825.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// LoginToIBuySpy - Use 'LoginToIBuySpyParams' to pass parameters into this method.
        /// </summary>
        public void LoginToIBuySpy()
        {
            #region Variable Declarations
            HtmlImage storecsvsimagessign_Image = this.InternetExplorerEnhaWindow.Httpmathewanweb5storClient.Httpmathewanweb5storDocument.Storecsvsimagessign_Image;
            HtmlEdit emailEdit = this.InternetExplorerEnhaWindow.Httpmathewanweb5storClient.Httpmathewanweb5storDocument1.EmailEdit;
            HtmlEdit passwordEdit = this.InternetExplorerEnhaWindow.Httpmathewanweb5storClient.Httpmathewanweb5storDocument1.PasswordEdit;
            HtmlInputButton loginBtnButton = this.InternetExplorerEnhaWindow.Httpmathewanweb5storClient.Httpmathewanweb5storDocument1.LoginBtnButton;
            #endregion

            // Go to web page 'http://mathewan-web5/storecsvs/default.aspx' using new browser instance
            this.InternetExplorerEnhaWindow.LaunchUrl(new System.Uri(this.LoginToIBuySpyParams.InternetExplorerEnhaWindowUrl));

            // Click '/storecsvs/images/sign_in.gif' image
            Mouse.Click(storecsvsimagessign_Image, new Point(21, 14));

            // Type 'jb@ibuyspy.com' in 'email' text box
            emailEdit.Text = this.LoginToIBuySpyParams.EmailEditText;

            // Type '{Tab}' in 'email' text box
            Keyboard.SendKeys(emailEdit, this.LoginToIBuySpyParams.EmailEditSendKeys, ModifierKeys.None);

            // Type '********' in 'password' text box
            passwordEdit.Password = this.LoginToIBuySpyParams.PasswordEditPassword;

            // Click 'LoginBtn' button
            Mouse.Click(loginBtnButton, new Point(59, 14));
        }
        
        /// <summary>
        /// PurchaseCommDevices - Use 'PurchaseCommDevicesParams' to pass parameters into this method.
        /// </summary>
        public void PurchaseCommDevices()
        {
            #region Variable Declarations
            HtmlHyperlink communicationsHyperlink = this.Httpmathewanweb5StorWindow.Httpmathewanweb5StorClient.Httpmathewanweb5StorDocument.CommunicationsHyperlink;
            HtmlHyperlink addToCartHyperlink = this.Httpmathewanweb5StorWindow.Httpmathewanweb5StorClient.Httpmathewanweb5StorDocument1.MyListTable.AddToCartHyperlink;
            HtmlEdit myList_ctl2QuantityEdit = this.Httpmathewanweb5StorWindow.Httpmathewanweb5StorClient.Httpmathewanweb5StorDocument2.MyList_ctl2QuantityEdit;
            HtmlInputButton updateBtnButton = this.Httpmathewanweb5StorWindow.Httpmathewanweb5StorClient.Httpmathewanweb5StorDocument2.UpdateBtnButton;
            #endregion

            // Click 'Communications' link
            Mouse.Click(communicationsHyperlink, new Point(87, 6));

            // Click 'Add To Cart' link
            Mouse.Click(addToCartHyperlink, new Point(53, 14));

            // Type '10' in 'MyList:_ctl2:Quantity' text box
            myList_ctl2QuantityEdit.Text = this.PurchaseCommDevicesParams.MyList_ctl2QuantityEditText;

            // Click 'UpdateBtn' button
            Mouse.Click(updateBtnButton, new Point(105, 12));
        }
        
        /// <summary>
        /// VerifyTotalSubTotal - Use 'VerifyTotalSubTotalExpectedValues' to pass parameters into this method.
        /// </summary>
        public void VerifyTotalSubTotal()
        {
            #region Variable Declarations
            HtmlSpan item49990Pane = this.Httpmathewanweb5StorWindow.Httpmathewanweb5StorClient.Httpmathewanweb5StorDocument2.Item49990Pane;
            HtmlCell item49990Cell = this.Httpmathewanweb5StorWindow.Httpmathewanweb5StorClient.Httpmathewanweb5StorDocument2.MyListTable.Item49990Cell;
            #endregion

            // Verify that '$499.90' pane's property 'InnerText' equals '$499.90'
            Assert.AreEqual(this.VerifyTotalSubTotalExpectedValues.Item49990PaneInnerText, item49990Pane.InnerText);

            // Verify that '$499.90' cell's property 'InnerText' equals '$499.90'
            Assert.AreEqual(this.VerifyTotalSubTotalExpectedValues.Item49990CellInnerText, item49990Cell.InnerText);
        }
        
        /// <summary>
        /// CompleteTransaction
        /// </summary>
        public void CompleteTransaction()
        {
            #region Variable Declarations
            HtmlInputButton checkoutBtnButton = this.Httpmathewanweb5StorWindow.Httpmathewanweb5StorClient.Httpmathewanweb5StorDocument2.CheckoutBtnButton;
            HtmlInputButton submitBtnButton = this.Httpmathewanweb5StorWindow.Httpmathewanweb5StorClient.Httpmathewanweb5StorDocument11.SubmitBtnButton;
            WinButton closeButton = this.Httpmathewanweb5StorWindow.Httpmathewanweb5StorTitleBar.CloseButton;
            #endregion

            // Click 'CheckoutBtn' button
            Mouse.Click(checkoutBtnButton, new Point(97, 16));

            // Click 'SubmitBtn' button
            Mouse.Click(submitBtnButton, new Point(53, 10));

            // Click 'Close' button
            Mouse.Click(closeButton, new Point(9, 11));
        }
        
        #region Properties
        public virtual LoginToIBuySpyParams LoginToIBuySpyParams
        {
            get
            {
                if ((this.mLoginToIBuySpyParams == null))
                {
                    this.mLoginToIBuySpyParams = new LoginToIBuySpyParams();
                }
                return this.mLoginToIBuySpyParams;
            }
        }
        
        public virtual PurchaseCommDevicesParams PurchaseCommDevicesParams
        {
            get
            {
                if ((this.mPurchaseCommDevicesParams == null))
                {
                    this.mPurchaseCommDevicesParams = new PurchaseCommDevicesParams();
                }
                return this.mPurchaseCommDevicesParams;
            }
        }
        
        public virtual VerifyTotalSubTotalExpectedValues VerifyTotalSubTotalExpectedValues
        {
            get
            {
                if ((this.mVerifyTotalSubTotalExpectedValues == null))
                {
                    this.mVerifyTotalSubTotalExpectedValues = new VerifyTotalSubTotalExpectedValues();
                }
                return this.mVerifyTotalSubTotalExpectedValues;
            }
        }
        
        public InternetExplorerEnhaWindow InternetExplorerEnhaWindow
        {
            get
            {
                if ((this.mInternetExplorerEnhaWindow == null))
                {
                    this.mInternetExplorerEnhaWindow = new InternetExplorerEnhaWindow();
                }
                return this.mInternetExplorerEnhaWindow;
            }
        }
        
        public Httpmathewanweb5StorWindow Httpmathewanweb5StorWindow
        {
            get
            {
                if ((this.mHttpmathewanweb5StorWindow == null))
                {
                    this.mHttpmathewanweb5StorWindow = new Httpmathewanweb5StorWindow();
                }
                return this.mHttpmathewanweb5StorWindow;
            }
        }
        #endregion
        
        #region Fields
        private LoginToIBuySpyParams mLoginToIBuySpyParams;
        
        private PurchaseCommDevicesParams mPurchaseCommDevicesParams;
        
        private VerifyTotalSubTotalExpectedValues mVerifyTotalSubTotalExpectedValues;
        
        private InternetExplorerEnhaWindow mInternetExplorerEnhaWindow;
        
        private Httpmathewanweb5StorWindow mHttpmathewanweb5StorWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LoginToIBuySpy'
    /// </summary>
    public class LoginToIBuySpyParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://mathewan-web5/storecsvs/default.aspx' using new browser instance
        /// </summary>
        public string InternetExplorerEnhaWindowUrl = "http://mathewan-web5/storecsvs/default.aspx";
        
        /// <summary>
        /// Type 'jb@ibuyspy.com' in 'email' text box
        /// </summary>
        public string EmailEditText = "jb@ibuyspy.com";
        
        /// <summary>
        /// Type '{Tab}' in 'email' text box
        /// </summary>
        public string EmailEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'password' text box
        /// </summary>
        public string PasswordEditPassword = "+0X0DdGy1Q17SNKZWOThMMM5Z2/vYWHQ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'PurchaseCommDevices'
    /// </summary>
    public class PurchaseCommDevicesParams
    {
        
        #region Fields
        /// <summary>
        /// Type '10' in 'MyList:_ctl2:Quantity' text box
        /// </summary>
        public string MyList_ctl2QuantityEditText = "10";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'VerifyTotalSubTotal'
    /// </summary>
    public class VerifyTotalSubTotalExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that '$499.90' pane's property 'InnerText' equals '$499.90'
        /// </summary>
        public string Item49990PaneInnerText = "$499.90";
        
        /// <summary>
        /// Verify that '$499.90' cell's property 'InnerText' equals '$499.90'
        /// </summary>
        public string Item49990CellInnerText = "$499.90";
        #endregion
    }
    
    public class InternetExplorerEnhaWindow : BrowserWindow
    {
        
        public InternetExplorerEnhaWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControlProperties.Common.Name, "Internet Explorer Enhanced Security Configuration is not enabled", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControlProperties.Common.ClassName] = "IEFrame";
            this.WindowTitles.Add("Internet Explorer Enhanced Security Configuration is not enabled - Windows Intern" +
                    "et Explorer");
            this.WindowTitles.Add("http://mathewan-web5/storecsvs/default.aspx - Windows Internet Explorer");
            this.WindowTitles.Add("http://mathewan-web5/storecsvs/Login.aspx - Windows Internet Explorer");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public Httpmathewanweb5storClient Httpmathewanweb5storClient
        {
            get
            {
                if ((this.mHttpmathewanweb5storClient == null))
                {
                    this.mHttpmathewanweb5storClient = new Httpmathewanweb5storClient(this);
                }
                return this.mHttpmathewanweb5storClient;
            }
        }
        #endregion
        
        #region Fields
        private Httpmathewanweb5storClient mHttpmathewanweb5storClient;
        #endregion
    }
    
    public class Httpmathewanweb5storClient : WinClient
    {
        
        public Httpmathewanweb5storClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinProperties.Client.ClassName] = "Internet Explorer_Server";
            this.WindowTitles.Add("http://mathewan-web5/storecsvs/default.aspx - Windows Internet Explorer");
            this.WindowTitles.Add("http://mathewan-web5/storecsvs/Login.aspx - Windows Internet Explorer");
            #endregion
        }
        
        #region Properties
        public Httpmathewanweb5storDocument Httpmathewanweb5storDocument
        {
            get
            {
                if ((this.mHttpmathewanweb5storDocument == null))
                {
                    this.mHttpmathewanweb5storDocument = new Httpmathewanweb5storDocument(this);
                }
                return this.mHttpmathewanweb5storDocument;
            }
        }
        
        public Httpmathewanweb5storDocument1 Httpmathewanweb5storDocument1
        {
            get
            {
                if ((this.mHttpmathewanweb5storDocument1 == null))
                {
                    this.mHttpmathewanweb5storDocument1 = new Httpmathewanweb5storDocument1(this);
                }
                return this.mHttpmathewanweb5storDocument1;
            }
        }
        #endregion
        
        #region Fields
        private Httpmathewanweb5storDocument mHttpmathewanweb5storDocument;
        
        private Httpmathewanweb5storDocument1 mHttpmathewanweb5storDocument1;
        #endregion
    }
    
    public class Httpmathewanweb5storDocument : HtmlDocument
    {
        
        public Httpmathewanweb5storDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlProperties.Document.Id] = null;
            this.SearchProperties[HtmlProperties.Document.RedirectingPage] = "False";
            this.SearchProperties[HtmlProperties.Document.FrameDocument] = "False";
            this.FilterProperties[HtmlProperties.Document.Title] = null;
            this.FilterProperties[HtmlProperties.Document.AbsolutePath] = "/storecsvs/default.aspx";
            this.FilterProperties[HtmlProperties.Document.PageUrl] = "http://mathewan-web5/storecsvs/default.aspx";
            this.WindowTitles.Add("http://mathewan-web5/storecsvs/default.aspx - Windows Internet Explorer");
            #endregion
        }
        
        #region Properties
        public HtmlImage Storecsvsimagessign_Image
        {
            get
            {
                if ((this.mStorecsvsimagessign_Image == null))
                {
                    this.mStorecsvsimagessign_Image = new HtmlImage(this);
                    #region Search Criteria
                    this.mStorecsvsimagessign_Image.SearchProperties[HtmlProperties.Image.Id] = null;
                    this.mStorecsvsimagessign_Image.SearchProperties[HtmlProperties.Image.Name] = null;
                    this.mStorecsvsimagessign_Image.SearchProperties[HtmlProperties.Image.Alt] = null;
                    this.mStorecsvsimagessign_Image.FilterProperties[HtmlProperties.Image.AbsolutePath] = "/storecsvs/images/sign_in.gif";
                    this.mStorecsvsimagessign_Image.FilterProperties[HtmlProperties.Image.Src] = "http://mathewan-web5/storecsvs/images/sign_in.gif";
                    this.mStorecsvsimagessign_Image.FilterProperties[HtmlProperties.Image.LinkAbsolutePath] = "/storecsvs/Login.aspx";
                    this.mStorecsvsimagessign_Image.FilterProperties[HtmlProperties.Image.Href] = "http://mathewan-web5/storecsvs/Login.aspx";
                    this.mStorecsvsimagessign_Image.FilterProperties[HtmlProperties.Image.Class] = null;
                    this.mStorecsvsimagessign_Image.FilterProperties[HtmlProperties.Image.ControlDefinition] = "border=0 src=\"images/sign_in.gif\"";
                    this.mStorecsvsimagessign_Image.FilterProperties[HtmlProperties.Image.TagInstance] = "2";
                    this.mStorecsvsimagessign_Image.WindowTitles.Add("http://mathewan-web5/storecsvs/default.aspx - Windows Internet Explorer");
                    #endregion
                }
                return this.mStorecsvsimagessign_Image;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mStorecsvsimagessign_Image;
        #endregion
    }
    
    public class Httpmathewanweb5storDocument1 : HtmlDocument
    {
        
        public Httpmathewanweb5storDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlProperties.Document.Id] = null;
            this.SearchProperties[HtmlProperties.Document.RedirectingPage] = "False";
            this.SearchProperties[HtmlProperties.Document.FrameDocument] = "False";
            this.FilterProperties[HtmlProperties.Document.Title] = null;
            this.FilterProperties[HtmlProperties.Document.AbsolutePath] = "/storecsvs/Login.aspx";
            this.FilterProperties[HtmlProperties.Document.PageUrl] = "http://mathewan-web5/storecsvs/Login.aspx";
            this.WindowTitles.Add("http://mathewan-web5/storecsvs/Login.aspx - Windows Internet Explorer");
            #endregion
        }
        
        #region Properties
        public HtmlEdit EmailEdit
        {
            get
            {
                if ((this.mEmailEdit == null))
                {
                    this.mEmailEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mEmailEdit.SearchProperties[HtmlProperties.Edit.Id] = "email";
                    this.mEmailEdit.SearchProperties[HtmlProperties.Edit.Name] = "email";
                    this.mEmailEdit.FilterProperties[HtmlProperties.Edit.LabeledBy] = null;
                    this.mEmailEdit.FilterProperties[HtmlProperties.Edit.Type] = "SINGLELINE";
                    this.mEmailEdit.FilterProperties[HtmlProperties.Edit.Title] = null;
                    this.mEmailEdit.FilterProperties[HtmlProperties.Edit.Class] = null;
                    this.mEmailEdit.FilterProperties[HtmlProperties.Edit.ControlDefinition] = "id=email size=25 name=email";
                    this.mEmailEdit.FilterProperties[HtmlProperties.Edit.TagInstance] = "7";
                    this.mEmailEdit.WindowTitles.Add("http://mathewan-web5/storecsvs/Login.aspx - Windows Internet Explorer");
                    #endregion
                }
                return this.mEmailEdit;
            }
        }
        
        public HtmlEdit PasswordEdit
        {
            get
            {
                if ((this.mPasswordEdit == null))
                {
                    this.mPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mPasswordEdit.SearchProperties[HtmlProperties.Edit.Id] = "password";
                    this.mPasswordEdit.SearchProperties[HtmlProperties.Edit.Name] = "password";
                    this.mPasswordEdit.FilterProperties[HtmlProperties.Edit.LabeledBy] = null;
                    this.mPasswordEdit.FilterProperties[HtmlProperties.Edit.Type] = "PASSWORD";
                    this.mPasswordEdit.FilterProperties[HtmlProperties.Edit.Title] = null;
                    this.mPasswordEdit.FilterProperties[HtmlProperties.Edit.Class] = null;
                    this.mPasswordEdit.FilterProperties[HtmlProperties.Edit.ControlDefinition] = "id=password value=\"\" size=25 type=passwo";
                    this.mPasswordEdit.FilterProperties[HtmlProperties.Edit.TagInstance] = "8";
                    this.mPasswordEdit.WindowTitles.Add("http://mathewan-web5/storecsvs/Login.aspx - Windows Internet Explorer");
                    #endregion
                }
                return this.mPasswordEdit;
            }
        }
        
        public HtmlInputButton LoginBtnButton
        {
            get
            {
                if ((this.mLoginBtnButton == null))
                {
                    this.mLoginBtnButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mLoginBtnButton.SearchProperties[HtmlProperties.Button.Id] = "LoginBtn";
                    this.mLoginBtnButton.SearchProperties[HtmlProperties.Button.Name] = "LoginBtn";
                    this.mLoginBtnButton.FilterProperties[HtmlProperties.Button.DisplayText] = null;
                    this.mLoginBtnButton.FilterProperties[HtmlProperties.Button.Type] = "image";
                    this.mLoginBtnButton.FilterProperties["Src"] = "http://mathewan-web5/storecsvs/images/sign_in_now.gif";
                    this.mLoginBtnButton.FilterProperties[HtmlProperties.Button.Title] = null;
                    this.mLoginBtnButton.FilterProperties[HtmlProperties.Button.Class] = null;
                    this.mLoginBtnButton.FilterProperties[HtmlProperties.Button.ControlDefinition] = "id=LoginBtn language=javascript onclick=";
                    this.mLoginBtnButton.FilterProperties[HtmlProperties.Button.TagInstance] = "10";
                    this.mLoginBtnButton.WindowTitles.Add("http://mathewan-web5/storecsvs/Login.aspx - Windows Internet Explorer");
                    #endregion
                }
                return this.mLoginBtnButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mEmailEdit;
        
        private HtmlEdit mPasswordEdit;
        
        private HtmlInputButton mLoginBtnButton;
        #endregion
    }
    
    public class Httpmathewanweb5StorWindow : BrowserWindow
    {
        
        public Httpmathewanweb5StorWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(UITestControlProperties.Common.Name, "http://mathewan-web5/StoreCSVS/default.aspx", PropertyExpressionOperator.Contains));
            this.SearchProperties[UITestControlProperties.Common.ClassName] = "IEFrame";
            this.WindowTitles.Add("http://mathewan-web5/StoreCSVS/default.aspx - Windows Internet Explorer");
            this.WindowTitles.Add("http://mathewan-web5/StoreCSVS/productslist.aspx?CategoryID=14&selection=0 - Wind" +
                    "ows Internet Explorer");
            this.WindowTitles.Add("http://mathewan-web5/StoreCSVS/ShoppingCart.aspx - Windows Internet Explorer");
            this.WindowTitles.Add("http://mathewan-web5/StoreCSVS/Checkout.aspx - Windows Internet Explorer");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public Httpmathewanweb5StorClient Httpmathewanweb5StorClient
        {
            get
            {
                if ((this.mHttpmathewanweb5StorClient == null))
                {
                    this.mHttpmathewanweb5StorClient = new Httpmathewanweb5StorClient(this);
                }
                return this.mHttpmathewanweb5StorClient;
            }
        }
        
        public Httpmathewanweb5StorTitleBar Httpmathewanweb5StorTitleBar
        {
            get
            {
                if ((this.mHttpmathewanweb5StorTitleBar == null))
                {
                    this.mHttpmathewanweb5StorTitleBar = new Httpmathewanweb5StorTitleBar(this);
                }
                return this.mHttpmathewanweb5StorTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private Httpmathewanweb5StorClient mHttpmathewanweb5StorClient;
        
        private Httpmathewanweb5StorTitleBar mHttpmathewanweb5StorTitleBar;
        #endregion
    }
    
    public class Httpmathewanweb5StorClient : WinClient
    {
        
        public Httpmathewanweb5StorClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinProperties.Client.ClassName] = "Internet Explorer_Server";
            this.WindowTitles.Add("http://mathewan-web5/StoreCSVS/default.aspx - Windows Internet Explorer");
            this.WindowTitles.Add("http://mathewan-web5/StoreCSVS/productslist.aspx?CategoryID=14&selection=0 - Wind" +
                    "ows Internet Explorer");
            this.WindowTitles.Add("http://mathewan-web5/StoreCSVS/ShoppingCart.aspx - Windows Internet Explorer");
            this.WindowTitles.Add("http://mathewan-web5/StoreCSVS/Checkout.aspx - Windows Internet Explorer");
            #endregion
        }
        
        #region Properties
        public Httpmathewanweb5StorDocument Httpmathewanweb5StorDocument
        {
            get
            {
                if ((this.mHttpmathewanweb5StorDocument == null))
                {
                    this.mHttpmathewanweb5StorDocument = new Httpmathewanweb5StorDocument(this);
                }
                return this.mHttpmathewanweb5StorDocument;
            }
        }
        
        public Httpmathewanweb5StorDocument1 Httpmathewanweb5StorDocument1
        {
            get
            {
                if ((this.mHttpmathewanweb5StorDocument1 == null))
                {
                    this.mHttpmathewanweb5StorDocument1 = new Httpmathewanweb5StorDocument1(this);
                }
                return this.mHttpmathewanweb5StorDocument1;
            }
        }
        
        public Httpmathewanweb5StorDocument2 Httpmathewanweb5StorDocument2
        {
            get
            {
                if ((this.mHttpmathewanweb5StorDocument2 == null))
                {
                    this.mHttpmathewanweb5StorDocument2 = new Httpmathewanweb5StorDocument2(this);
                }
                return this.mHttpmathewanweb5StorDocument2;
            }
        }
        
        public Httpmathewanweb5StorDocument11 Httpmathewanweb5StorDocument11
        {
            get
            {
                if ((this.mHttpmathewanweb5StorDocument11 == null))
                {
                    this.mHttpmathewanweb5StorDocument11 = new Httpmathewanweb5StorDocument11(this);
                }
                return this.mHttpmathewanweb5StorDocument11;
            }
        }
        #endregion
        
        #region Fields
        private Httpmathewanweb5StorDocument mHttpmathewanweb5StorDocument;
        
        private Httpmathewanweb5StorDocument1 mHttpmathewanweb5StorDocument1;
        
        private Httpmathewanweb5StorDocument2 mHttpmathewanweb5StorDocument2;
        
        private Httpmathewanweb5StorDocument11 mHttpmathewanweb5StorDocument11;
        #endregion
    }
    
    public class Httpmathewanweb5StorDocument : HtmlDocument
    {
        
        public Httpmathewanweb5StorDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlProperties.Document.Id] = null;
            this.SearchProperties[HtmlProperties.Document.RedirectingPage] = "False";
            this.SearchProperties[HtmlProperties.Document.FrameDocument] = "False";
            this.FilterProperties[HtmlProperties.Document.Title] = null;
            this.FilterProperties[HtmlProperties.Document.AbsolutePath] = "/StoreCSVS/default.aspx";
            this.FilterProperties[HtmlProperties.Document.PageUrl] = "http://mathewan-web5/StoreCSVS/default.aspx";
            this.WindowTitles.Add("http://mathewan-web5/StoreCSVS/default.aspx - Windows Internet Explorer");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink CommunicationsHyperlink
        {
            get
            {
                if ((this.mCommunicationsHyperlink == null))
                {
                    this.mCommunicationsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mCommunicationsHyperlink.SearchProperties[HtmlProperties.Hyperlink.Id] = "Menu1_MyList__ctl0_HyperLink1";
                    this.mCommunicationsHyperlink.SearchProperties[HtmlProperties.Hyperlink.Name] = null;
                    this.mCommunicationsHyperlink.SearchProperties[HtmlProperties.Hyperlink.Target] = null;
                    this.mCommunicationsHyperlink.SearchProperties[HtmlProperties.Hyperlink.InnerText] = "Communications";
                    this.mCommunicationsHyperlink.FilterProperties[HtmlProperties.Hyperlink.AbsolutePath] = "/StoreCSVS/productslist.aspx";
                    this.mCommunicationsHyperlink.FilterProperties[HtmlProperties.Hyperlink.Title] = null;
                    this.mCommunicationsHyperlink.FilterProperties[HtmlProperties.Hyperlink.Href] = "http://mathewan-web5/StoreCSVS/productslist.aspx?CategoryID=14&selection=0";
                    this.mCommunicationsHyperlink.FilterProperties[HtmlProperties.Hyperlink.Class] = "MenuUnselected";
                    this.mCommunicationsHyperlink.FilterProperties[HtmlProperties.Hyperlink.ControlDefinition] = "id=Menu1_MyList__ctl0_HyperLink1 class=M";
                    this.mCommunicationsHyperlink.FilterProperties[HtmlProperties.Hyperlink.TagInstance] = "6";
                    this.mCommunicationsHyperlink.WindowTitles.Add("http://mathewan-web5/StoreCSVS/default.aspx - Windows Internet Explorer");
                    #endregion
                }
                return this.mCommunicationsHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mCommunicationsHyperlink;
        #endregion
    }
    
    public class Httpmathewanweb5StorDocument1 : HtmlDocument
    {
        
        public Httpmathewanweb5StorDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlProperties.Document.Id] = null;
            this.SearchProperties[HtmlProperties.Document.RedirectingPage] = "False";
            this.SearchProperties[HtmlProperties.Document.FrameDocument] = "False";
            this.FilterProperties[HtmlProperties.Document.Title] = null;
            this.FilterProperties[HtmlProperties.Document.AbsolutePath] = "/StoreCSVS/productslist.aspx";
            this.FilterProperties[HtmlProperties.Document.PageUrl] = "http://mathewan-web5/StoreCSVS/productslist.aspx?CategoryID=14&selection=0";
            this.WindowTitles.Add("http://mathewan-web5/StoreCSVS/productslist.aspx?CategoryID=14&selection=0 - Wind" +
                    "ows Internet Explorer");
            #endregion
        }
        
        #region Properties
        public MyListTable MyListTable
        {
            get
            {
                if ((this.mMyListTable == null))
                {
                    this.mMyListTable = new MyListTable(this);
                }
                return this.mMyListTable;
            }
        }
        #endregion
        
        #region Fields
        private MyListTable mMyListTable;
        #endregion
    }
    
    public class MyListTable : HtmlTable
    {
        
        public MyListTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlProperties.Table.Id] = "MyList";
            this.SearchProperties[HtmlProperties.Table.Name] = null;
            this.FilterProperties[HtmlProperties.Table.InnerText] = "   Communications Device \r\nSpecial Price";
            this.FilterProperties[HtmlProperties.Table.ControlDefinition] = "style=\"BORDER-COLLAPSE: collapse\" id=MyL";
            this.FilterProperties[HtmlProperties.Table.RowCount] = "3";
            this.FilterProperties[HtmlProperties.Table.ColumnCount] = "2";
            this.FilterProperties[HtmlProperties.Table.Class] = null;
            this.FilterProperties[HtmlProperties.Table.TagInstance] = "9";
            this.WindowTitles.Add("http://mathewan-web5/StoreCSVS/productslist.aspx?CategoryID=14&selection=0 - Wind" +
                    "ows Internet Explorer");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink AddToCartHyperlink
        {
            get
            {
                if ((this.mAddToCartHyperlink == null))
                {
                    this.mAddToCartHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mAddToCartHyperlink.SearchProperties[HtmlProperties.Hyperlink.Id] = null;
                    this.mAddToCartHyperlink.SearchProperties[HtmlProperties.Hyperlink.Name] = null;
                    this.mAddToCartHyperlink.SearchProperties[HtmlProperties.Hyperlink.Target] = null;
                    this.mAddToCartHyperlink.SearchProperties[HtmlProperties.Hyperlink.InnerText] = "Add To Cart ";
                    this.mAddToCartHyperlink.FilterProperties[HtmlProperties.Hyperlink.AbsolutePath] = "/StoreCSVS/AddToCart.aspx";
                    this.mAddToCartHyperlink.FilterProperties[HtmlProperties.Hyperlink.Title] = null;
                    this.mAddToCartHyperlink.FilterProperties[HtmlProperties.Hyperlink.Href] = "http://mathewan-web5/StoreCSVS/AddToCart.aspx?productID=360";
                    this.mAddToCartHyperlink.FilterProperties[HtmlProperties.Hyperlink.Class] = null;
                    this.mAddToCartHyperlink.FilterProperties[HtmlProperties.Hyperlink.ControlDefinition] = "href=\"AddToCart.aspx?productID=360\"";
                    this.mAddToCartHyperlink.FilterProperties[HtmlProperties.Hyperlink.TagInstance] = "3";
                    this.mAddToCartHyperlink.WindowTitles.Add("http://mathewan-web5/StoreCSVS/productslist.aspx?CategoryID=14&selection=0 - Wind" +
                            "ows Internet Explorer");
                    #endregion
                }
                return this.mAddToCartHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mAddToCartHyperlink;
        #endregion
    }
    
    public class Httpmathewanweb5StorDocument2 : HtmlDocument
    {
        
        public Httpmathewanweb5StorDocument2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlProperties.Document.Id] = null;
            this.SearchProperties[HtmlProperties.Document.RedirectingPage] = "False";
            this.SearchProperties[HtmlProperties.Document.FrameDocument] = "False";
            this.FilterProperties[HtmlProperties.Document.Title] = null;
            this.FilterProperties[HtmlProperties.Document.AbsolutePath] = "/StoreCSVS/ShoppingCart.aspx";
            this.FilterProperties[HtmlProperties.Document.PageUrl] = "http://mathewan-web5/StoreCSVS/ShoppingCart.aspx";
            this.WindowTitles.Add("http://mathewan-web5/StoreCSVS/ShoppingCart.aspx - Windows Internet Explorer");
            #endregion
        }
        
        #region Properties
        public HtmlEdit MyList_ctl2QuantityEdit
        {
            get
            {
                if ((this.mMyList_ctl2QuantityEdit == null))
                {
                    this.mMyList_ctl2QuantityEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mMyList_ctl2QuantityEdit.SearchProperties[HtmlProperties.Edit.Id] = "MyList__ctl2_Quantity";
                    this.mMyList_ctl2QuantityEdit.SearchProperties[HtmlProperties.Edit.Name] = "MyList:_ctl2:Quantity";
                    this.mMyList_ctl2QuantityEdit.FilterProperties[HtmlProperties.Edit.LabeledBy] = null;
                    this.mMyList_ctl2QuantityEdit.FilterProperties[HtmlProperties.Edit.Type] = "SINGLELINE";
                    this.mMyList_ctl2QuantityEdit.FilterProperties[HtmlProperties.Edit.Title] = null;
                    this.mMyList_ctl2QuantityEdit.FilterProperties[HtmlProperties.Edit.Class] = null;
                    this.mMyList_ctl2QuantityEdit.FilterProperties[HtmlProperties.Edit.ControlDefinition] = "style=\"WIDTH: 40px\" id=MyList__ctl2_Quan";
                    this.mMyList_ctl2QuantityEdit.FilterProperties[HtmlProperties.Edit.TagInstance] = "5";
                    this.mMyList_ctl2QuantityEdit.WindowTitles.Add("http://mathewan-web5/StoreCSVS/ShoppingCart.aspx - Windows Internet Explorer");
                    #endregion
                }
                return this.mMyList_ctl2QuantityEdit;
            }
        }
        
        public HtmlInputButton UpdateBtnButton
        {
            get
            {
                if ((this.mUpdateBtnButton == null))
                {
                    this.mUpdateBtnButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUpdateBtnButton.SearchProperties[HtmlProperties.Button.Id] = "UpdateBtn";
                    this.mUpdateBtnButton.SearchProperties[HtmlProperties.Button.Name] = "UpdateBtn";
                    this.mUpdateBtnButton.FilterProperties[HtmlProperties.Button.DisplayText] = null;
                    this.mUpdateBtnButton.FilterProperties[HtmlProperties.Button.Type] = "image";
                    this.mUpdateBtnButton.FilterProperties["Src"] = "http://mathewan-web5/StoreCSVS/images/update_cart.gif";
                    this.mUpdateBtnButton.FilterProperties[HtmlProperties.Button.Title] = null;
                    this.mUpdateBtnButton.FilterProperties[HtmlProperties.Button.Class] = null;
                    this.mUpdateBtnButton.FilterProperties[HtmlProperties.Button.ControlDefinition] = "id=UpdateBtn src=\"images/update_cart.gif";
                    this.mUpdateBtnButton.FilterProperties[HtmlProperties.Button.TagInstance] = "7";
                    this.mUpdateBtnButton.WindowTitles.Add("http://mathewan-web5/StoreCSVS/ShoppingCart.aspx - Windows Internet Explorer");
                    #endregion
                }
                return this.mUpdateBtnButton;
            }
        }
        
        public MyListTable1 MyListTable
        {
            get
            {
                if ((this.mMyListTable == null))
                {
                    this.mMyListTable = new MyListTable1(this);
                }
                return this.mMyListTable;
            }
        }
        
        public HtmlSpan Item49990Pane
        {
            get
            {
                if ((this.mItem49990Pane == null))
                {
                    this.mItem49990Pane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mItem49990Pane.SearchProperties[HtmlProperties.Pane.Id] = "lblTotal";
                    this.mItem49990Pane.SearchProperties[HtmlProperties.Pane.Name] = null;
                    this.mItem49990Pane.FilterProperties[HtmlProperties.Pane.InnerText] = "$499.90";
                    this.mItem49990Pane.FilterProperties[HtmlProperties.Pane.Title] = null;
                    this.mItem49990Pane.FilterProperties[HtmlProperties.Pane.Class] = "NormalBold";
                    this.mItem49990Pane.FilterProperties[HtmlProperties.Pane.ControlDefinition] = "id=lblTotal class=NormalBold";
                    this.mItem49990Pane.FilterProperties[HtmlProperties.Pane.TagInstance] = "4";
                    this.mItem49990Pane.WindowTitles.Add("http://mathewan-web5/StoreCSVS/ShoppingCart.aspx - Windows Internet Explorer");
                    #endregion
                }
                return this.mItem49990Pane;
            }
        }
        
        public HtmlInputButton CheckoutBtnButton
        {
            get
            {
                if ((this.mCheckoutBtnButton == null))
                {
                    this.mCheckoutBtnButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mCheckoutBtnButton.SearchProperties[HtmlProperties.Button.Id] = "CheckoutBtn";
                    this.mCheckoutBtnButton.SearchProperties[HtmlProperties.Button.Name] = "CheckoutBtn";
                    this.mCheckoutBtnButton.FilterProperties[HtmlProperties.Button.DisplayText] = null;
                    this.mCheckoutBtnButton.FilterProperties[HtmlProperties.Button.Type] = "image";
                    this.mCheckoutBtnButton.FilterProperties["Src"] = "http://mathewan-web5/StoreCSVS/images/final_checkout.gif";
                    this.mCheckoutBtnButton.FilterProperties[HtmlProperties.Button.Title] = null;
                    this.mCheckoutBtnButton.FilterProperties[HtmlProperties.Button.Class] = null;
                    this.mCheckoutBtnButton.FilterProperties[HtmlProperties.Button.ControlDefinition] = "id=CheckoutBtn src=\"images/final_checkou";
                    this.mCheckoutBtnButton.FilterProperties[HtmlProperties.Button.TagInstance] = "8";
                    this.mCheckoutBtnButton.WindowTitles.Add("http://mathewan-web5/StoreCSVS/ShoppingCart.aspx - Windows Internet Explorer");
                    #endregion
                }
                return this.mCheckoutBtnButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mMyList_ctl2QuantityEdit;
        
        private HtmlInputButton mUpdateBtnButton;
        
        private MyListTable1 mMyListTable;
        
        private HtmlSpan mItem49990Pane;
        
        private HtmlInputButton mCheckoutBtnButton;
        #endregion
    }
    
    public class MyListTable1 : HtmlTable
    {
        
        public MyListTable1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlProperties.Table.Id] = "MyList";
            this.SearchProperties[HtmlProperties.Table.Name] = null;
            this.FilterProperties[HtmlProperties.Table.InnerText] = "Product IDProduct NameModelQuantityPrice";
            this.FilterProperties[HtmlProperties.Table.ControlDefinition] = "style=\"BORDER-BOTTOM-COLOR: black; BORDE";
            this.FilterProperties[HtmlProperties.Table.RowCount] = "3";
            this.FilterProperties[HtmlProperties.Table.ColumnCount] = "7";
            this.FilterProperties[HtmlProperties.Table.Class] = null;
            this.FilterProperties[HtmlProperties.Table.TagInstance] = "11";
            this.WindowTitles.Add("http://mathewan-web5/StoreCSVS/ShoppingCart.aspx - Windows Internet Explorer");
            #endregion
        }
        
        #region Properties
        public HtmlCell Item49990Cell
        {
            get
            {
                if ((this.mItem49990Cell == null))
                {
                    this.mItem49990Cell = new HtmlCell(this);
                    #region Search Criteria
                    this.mItem49990Cell.SearchProperties[HtmlProperties.Cell.Id] = null;
                    this.mItem49990Cell.SearchProperties[HtmlProperties.Cell.Name] = null;
                    this.mItem49990Cell.SearchProperties[HtmlProperties.Cell.MaxDepth] = "3";
                    this.mItem49990Cell.FilterProperties[HtmlProperties.Cell.InnerText] = "$499.90";
                    this.mItem49990Cell.FilterProperties[HtmlProperties.Cell.ControlDefinition] = null;
                    this.mItem49990Cell.FilterProperties[HtmlProperties.Cell.RowIndex] = "1";
                    this.mItem49990Cell.FilterProperties[HtmlProperties.Cell.ColumnIndex] = "5";
                    this.mItem49990Cell.FilterProperties[HtmlProperties.Cell.Class] = null;
                    this.mItem49990Cell.FilterProperties[HtmlProperties.Cell.TagInstance] = "13";
                    this.mItem49990Cell.WindowTitles.Add("http://mathewan-web5/StoreCSVS/ShoppingCart.aspx - Windows Internet Explorer");
                    #endregion
                }
                return this.mItem49990Cell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mItem49990Cell;
        #endregion
    }
    
    public class Httpmathewanweb5StorDocument11 : HtmlDocument
    {
        
        public Httpmathewanweb5StorDocument11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlProperties.Document.Id] = null;
            this.SearchProperties[HtmlProperties.Document.RedirectingPage] = "False";
            this.SearchProperties[HtmlProperties.Document.FrameDocument] = "False";
            this.FilterProperties[HtmlProperties.Document.Title] = null;
            this.FilterProperties[HtmlProperties.Document.AbsolutePath] = "/StoreCSVS/Checkout.aspx";
            this.FilterProperties[HtmlProperties.Document.PageUrl] = "http://mathewan-web5/StoreCSVS/Checkout.aspx";
            this.WindowTitles.Add("http://mathewan-web5/StoreCSVS/Checkout.aspx - Windows Internet Explorer");
            #endregion
        }
        
        #region Properties
        public HtmlInputButton SubmitBtnButton
        {
            get
            {
                if ((this.mSubmitBtnButton == null))
                {
                    this.mSubmitBtnButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mSubmitBtnButton.SearchProperties[HtmlProperties.Button.Id] = "SubmitBtn";
                    this.mSubmitBtnButton.SearchProperties[HtmlProperties.Button.Name] = "SubmitBtn";
                    this.mSubmitBtnButton.FilterProperties[HtmlProperties.Button.DisplayText] = null;
                    this.mSubmitBtnButton.FilterProperties[HtmlProperties.Button.Type] = "image";
                    this.mSubmitBtnButton.FilterProperties["Src"] = "http://mathewan-web5/StoreCSVS/images/submit.gif";
                    this.mSubmitBtnButton.FilterProperties[HtmlProperties.Button.Title] = null;
                    this.mSubmitBtnButton.FilterProperties[HtmlProperties.Button.Class] = null;
                    this.mSubmitBtnButton.FilterProperties[HtmlProperties.Button.ControlDefinition] = "id=SubmitBtn src=\"images/submit.gif\" typ";
                    this.mSubmitBtnButton.FilterProperties[HtmlProperties.Button.TagInstance] = "5";
                    this.mSubmitBtnButton.WindowTitles.Add("http://mathewan-web5/StoreCSVS/Checkout.aspx - Windows Internet Explorer");
                    #endregion
                }
                return this.mSubmitBtnButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlInputButton mSubmitBtnButton;
        #endregion
    }
    
    public class Httpmathewanweb5StorTitleBar : WinTitleBar
    {
        
        public Httpmathewanweb5StorTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("http://mathewan-web5/StoreCSVS/Checkout.aspx - Windows Internet Explorer");
            #endregion
        }
        
        #region Properties
        public WinButton CloseButton
        {
            get
            {
                if ((this.mCloseButton == null))
                {
                    this.mCloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mCloseButton.SearchProperties[WinProperties.Button.Name] = "Close";
                    this.mCloseButton.WindowTitles.Add("http://mathewan-web5/StoreCSVS/Checkout.aspx - Windows Internet Explorer");
                    #endregion
                }
                return this.mCloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mCloseButton;
        #endregion
    }
}
